Add documentation of the mqtt spec
equinor/flotilla-openapi pull request #8
Opened 2022-02-16 07:42 UTC by vetlek

2022-02-17 10:17 UTC, aestene commented on mqtt_spec.yaml
> +    time data about robots and missions on an Equinor asset.
```suggestion
    Flotilla MQTT API is a streaming broker for producers and cosnumers of real
    time data about robots and missions on facility.
```

2022-02-17 10:19 UTC, aestene commented on mqtt_spec.yaml
> +    url: https://www.apache.org/licenses/LICENSE-2.0
Shouldn't this be the license of Flotilla which is EPL 2.0?

2022-02-17 10:23 UTC, aestene commented on mqtt_spec.yaml
> +      - user-password: []
Can you add `mosquitto` as user and `default` as password here? Those as the default values that are openly available anyway.

2022-02-17 11:04 UTC, vetlek commented on mqtt_spec.yaml
> +      - user-password: []
Couldn't find anything in the documentation about adding this, so don't think it is possible

2022-02-18 09:35 UTC, aestene commented on mqtt_spec.yaml
> +      description: Date and time when the message was sent.
```suggestion
    timestamp:
      type: string
      format: date-time
      description: Date and time when the message was sent.
```
```suggestion
    sentAt:
      type: string
      format: date-time
      description: Date and time when the message was sent.
```

2022-02-18 09:35 UTC, aestene commented on mqtt_spec.yaml
> +          $ref: '#/components/schemas/sentAt'
```suggestion
        timestamp:
          $ref: '#/components/schemas/timestamp'
```
```suggestion
        sent_at:
          $ref: '#/components/schemas/sentAt'
```

2022-02-18 09:36 UTC, aestene commented on mqtt_spec.yaml
> +          $ref: '#/components/schemas/sentAt'
```suggestion
        timestamp:
          $ref: '#/components/schemas/timestamp'
```
```suggestion
        sent_at:
          $ref: '#/components/schemas/sentAt'
```

2022-02-18 09:37 UTC, aestene commented on mqtt_spec.yaml
> +          $ref: '#/components/schemas/sentAt'
```suggestion
        timestamp:
          $ref: '#/components/schemas/timestamp'
```

2022-02-18 09:37 UTC, aestene commented on mqtt_spec.yaml
> +          $ref: '#/components/schemas/sentAt'
```suggestion
        timestamp:
          $ref: '#/components/schemas/timestamp'
```

2022-02-18 09:55 UTC, aestene requested changes
Have a look at the comments but otherwise this looks very good! I think it will be very useful :tada:

2022-02-18 11:42 UTC, merged